services:
  - type: web
    name: ctrlscroll-web
    env: node
    plan: starter
    rootDir: apps/web
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: PUBLIC_ORIGIN
        fromService:
          type: web
          name: ctrlscroll-web
          property: url
      - key: DATA_DIR
        value: /data
    disk:
      name: ctrlscroll-disk
      mountPath: /data
      sizeGB: 1

  - type: web
    name: ctrlscroll-api
    env: node
    plan: starter
    rootDir: apps/api
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: DATA_DIR
        value: /data
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASS
        sync: false
      - key: PUBLIC_ORIGIN
        value: https://ctrlscroll.com
    disk:
      name: ctrlscroll-disk
      mountPath: /data
      sizeGB: 1

  - type: worker
    name: ctrlscroll-worker
    env: node
    plan: starter
    rootDir: apps/worker
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: DATA_DIR
        value: /data
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USERNAME
        sync: false
      - key: REDDIT_PASSWORD
        sync: false
      - key: REDDIT_USER_AGENT
        value: CtrlScrollBot/2.0 by u/<yourname>
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASS
        sync: false
      - key: PUBLIC_ORIGIN
        value: https://ctrlscroll.com
    disk:
      name: ctrlscroll-disk
      mountPath: /data
      sizeGB: 1

scheduledJobs:
  - name: ingest-watchlists
    schedule: "*/5 * * * *"
    webServiceName: ctrlscroll-worker
    endpoint: /internal/run/ingest
    headers:
      Authorization: "Basic {{BASIC_AUTH_USER}}:{{BASIC_AUTH_PASS}}"
  - name: refresh-hot
    schedule: "*/10 * * * *"
    webServiceName: ctrlscroll-worker
    endpoint: /internal/run/refresh
    headers:
      Authorization: "Basic {{BASIC_AUTH_USER}}:{{BASIC_AUTH_PASS}}"
  - name: rebuild-feeds
    schedule: "@hourly"
    webServiceName: ctrlscroll-worker
    endpoint: /internal/run/feeds
    headers:
      Authorization: "Basic {{BASIC_AUTH_USER}}:{{BASIC_AUTH_PASS}}"