services:
  - type: web
    name: ctrlscroll
    env: node
    plan: starter
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: PUBLIC_ORIGIN
        fromService:
          type: web
          name: ctrlscroll
          property: url
      - key: DATA_DIR
        value: /data
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USERNAME
        sync: false
      - key: REDDIT_PASSWORD
        sync: false
      - key: REDDIT_USER_AGENT
        value: CtrlScrollBot/2.0 by u/<yourname>
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_VERIFICATION
        sync: false
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASS
        sync: false
    disk:
      name: ctrlscroll-disk
      mountPath: /data
      sizeGB: 1

scheduledJobs:
  - name: ingest-watchlists
    schedule: "*/5 * * * *"
    webServiceName: ctrlscroll
    endpoint: /api/ingest
    headers:
      Authorization: "Basic {{BASIC_AUTH_USER}}:{{BASIC_AUTH_PASS}}"
  - name: refresh-hot
    schedule: "*/10 * * * *"
    webServiceName: ctrlscroll
    endpoint: /api/refresh
    headers:
      Authorization: "Basic {{BASIC_AUTH_USER}}:{{BASIC_AUTH_PASS}}"
  - name: rebuild-feeds
    schedule: "@hourly"
    webServiceName: ctrlscroll
    endpoint: /api/feeds
    headers:
      Authorization: "Basic {{BASIC_AUTH_USER}}:{{BASIC_AUTH_PASS}}"