'use client';

import { useEffect, useState } from 'react';
import PostCard from '../components/PostCard';
import { assignVariant, trackImpression } from '../lib/ab';

interface Post {
  id: string;
  title: string;
  micro: string;
  createdUtc: number;
  subreddit: string;
  score: number;
  tags: string[];
  permalink: string;
}

export default function HomePage() {
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchPosts() {
      try {
        const response = await fetch('/api/v1/posts?size=20');
        if (!response.ok) {
          throw new Error('Failed to fetch posts');
        }
        const data = await response.json();
        setPosts(data.items || []);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    }

    fetchPosts();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading posts...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="text-red-500 text-6xl mb-4">⚠️</div>
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Error Loading Posts</h1>
          <p className="text-gray-600">{error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-6xl mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">📜 Ctrl+Scroll</h1>
              <p className="text-gray-600 mt-1">AI-curated summaries from Reddit's top discussions</p>
            </div>
            <div className="flex items-center space-x-4">
              <a href="/v1/rss.xml" className="text-sm text-gray-500 hover:text-gray-700">
                RSS
              </a>
              <a href="/v1/feed.json" className="text-sm text-gray-500 hover:text-gray-700">
                JSON
              </a>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-4 py-8">
        {posts.length === 0 ? (
          <div className="text-center py-12">
            <div className="text-gray-400 text-6xl mb-4">📭</div>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">No Posts Yet</h2>
            <p className="text-gray-600">Check back later for new content!</p>
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-semibold text-gray-900">
                Latest Posts ({posts.length})
              </h2>
              <div className="flex items-center space-x-2">
                <span className="text-sm text-gray-500">Live updates</span>
                <span className="badge badge-live">LIVE</span>
              </div>
            </div>

            <div className="grid gap-6">
              {posts.map((post, index) => (
                <PostCard
                  key={post.id}
                  post={post}
                  index={index}
                  variant={assignVariant(post.id)}
                  onImpression={() => trackImpression(post.id, assignVariant(post.id))}
                />
              ))}
            </div>

            <div className="mt-12 text-center">
              <p className="text-sm text-gray-500">
                Content sourced from Reddit • Generated by Ctrl+Scroll
              </p>
            </div>
          </>
        )}
      </main>
    </div>
  );
}
